spring.application.name=hr
# server.port=7070
# 데이터 베이스 접속정보
spring.datasource.url=jdbc:mysql://43.201.71.210:3306/HR?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# xml 파일의 위치
mybatis.mapper-locations=classpath:mapper/*.xml
# resultType의 패키지 정보
mybatis.type-aliases-package=com.example.hr.dto
# 기본은 스네이크표기법을 따르므로 카멜표기법으로 변경
mybatis.configuration.map-underscore-to-camel-case=true

# 브라우져 새로고침시 수정사항이 바로바로 반영
spring.thymeleaf.cache=false